/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-15 at 21:51:42 UTC 
 * Modify at your own risk.
 */

package com.aqpup.model.spotshotendpoint.model;

/**
 * Model definition for Friendship.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the spotshotendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Friendship extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime acceptedDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer otherPredisposition;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer predisposition;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime requestDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long srcfriendId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long targetFriendId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String targetFriendUsername;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getAcceptedDate() {
    return acceptedDate;
  }

  /**
   * @param acceptedDate acceptedDate or {@code null} for none
   */
  public Friendship setAcceptedDate(com.google.api.client.util.DateTime acceptedDate) {
    this.acceptedDate = acceptedDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Friendship setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getOtherPredisposition() {
    return otherPredisposition;
  }

  /**
   * @param otherPredisposition otherPredisposition or {@code null} for none
   */
  public Friendship setOtherPredisposition(java.lang.Integer otherPredisposition) {
    this.otherPredisposition = otherPredisposition;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPredisposition() {
    return predisposition;
  }

  /**
   * @param predisposition predisposition or {@code null} for none
   */
  public Friendship setPredisposition(java.lang.Integer predisposition) {
    this.predisposition = predisposition;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getRequestDate() {
    return requestDate;
  }

  /**
   * @param requestDate requestDate or {@code null} for none
   */
  public Friendship setRequestDate(com.google.api.client.util.DateTime requestDate) {
    this.requestDate = requestDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getSrcfriendId() {
    return srcfriendId;
  }

  /**
   * @param srcfriendId srcfriendId or {@code null} for none
   */
  public Friendship setSrcfriendId(java.lang.Long srcfriendId) {
    this.srcfriendId = srcfriendId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTargetFriendId() {
    return targetFriendId;
  }

  /**
   * @param targetFriendId targetFriendId or {@code null} for none
   */
  public Friendship setTargetFriendId(java.lang.Long targetFriendId) {
    this.targetFriendId = targetFriendId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTargetFriendUsername() {
    return targetFriendUsername;
  }

  /**
   * @param targetFriendUsername targetFriendUsername or {@code null} for none
   */
  public Friendship setTargetFriendUsername(java.lang.String targetFriendUsername) {
    this.targetFriendUsername = targetFriendUsername;
    return this;
  }

  @Override
  public Friendship set(String fieldName, Object value) {
    return (Friendship) super.set(fieldName, value);
  }

  @Override
  public Friendship clone() {
    return (Friendship) super.clone();
  }

}
